//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnicaDB.ApplicationWeb.UsuarioService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioDto", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnicaDB.BLL.Dtos")]
    [System.SerializableAttribute()]
    public partial class UsuarioDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuarioService.IUsuarioService")]
    public interface IUsuarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/ListaUsuario", ReplyAction="http://tempuri.org/IUsuarioService/ListaUsuarioResponse")]
        PruebaTecnicaDB.ApplicationWeb.UsuarioService.UsuarioDto[] ListaUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/ListaUsuario", ReplyAction="http://tempuri.org/IUsuarioService/ListaUsuarioResponse")]
        System.Threading.Tasks.Task<PruebaTecnicaDB.ApplicationWeb.UsuarioService.UsuarioDto[]> ListaUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/ObtenerUsuarioPorId", ReplyAction="http://tempuri.org/IUsuarioService/ObtenerUsuarioPorIdResponse")]
        PruebaTecnicaDB.ApplicationWeb.UsuarioService.UsuarioDto ObtenerUsuarioPorId(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/ObtenerUsuarioPorId", ReplyAction="http://tempuri.org/IUsuarioService/ObtenerUsuarioPorIdResponse")]
        System.Threading.Tasks.Task<PruebaTecnicaDB.ApplicationWeb.UsuarioService.UsuarioDto> ObtenerUsuarioPorIdAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/CrearUsuario", ReplyAction="http://tempuri.org/IUsuarioService/CrearUsuarioResponse")]
        void CrearUsuario(PruebaTecnicaDB.ApplicationWeb.UsuarioService.UsuarioDto usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/CrearUsuario", ReplyAction="http://tempuri.org/IUsuarioService/CrearUsuarioResponse")]
        System.Threading.Tasks.Task CrearUsuarioAsync(PruebaTecnicaDB.ApplicationWeb.UsuarioService.UsuarioDto usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/EditarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/EditarUsuarioResponse")]
        void EditarUsuario(PruebaTecnicaDB.ApplicationWeb.UsuarioService.UsuarioDto usuario, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/EditarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/EditarUsuarioResponse")]
        System.Threading.Tasks.Task EditarUsuarioAsync(PruebaTecnicaDB.ApplicationWeb.UsuarioService.UsuarioDto usuario, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/EliminarUsuarioResponse")]
        void EliminarUsuario(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task EliminarUsuarioAsync(System.Nullable<int> id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServiceChannel : PruebaTecnicaDB.ApplicationWeb.UsuarioService.IUsuarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServiceClient : System.ServiceModel.ClientBase<PruebaTecnicaDB.ApplicationWeb.UsuarioService.IUsuarioService>, PruebaTecnicaDB.ApplicationWeb.UsuarioService.IUsuarioService {
        
        public UsuarioServiceClient() {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PruebaTecnicaDB.ApplicationWeb.UsuarioService.UsuarioDto[] ListaUsuario() {
            return base.Channel.ListaUsuario();
        }
        
        public System.Threading.Tasks.Task<PruebaTecnicaDB.ApplicationWeb.UsuarioService.UsuarioDto[]> ListaUsuarioAsync() {
            return base.Channel.ListaUsuarioAsync();
        }
        
        public PruebaTecnicaDB.ApplicationWeb.UsuarioService.UsuarioDto ObtenerUsuarioPorId(System.Nullable<int> id) {
            return base.Channel.ObtenerUsuarioPorId(id);
        }
        
        public System.Threading.Tasks.Task<PruebaTecnicaDB.ApplicationWeb.UsuarioService.UsuarioDto> ObtenerUsuarioPorIdAsync(System.Nullable<int> id) {
            return base.Channel.ObtenerUsuarioPorIdAsync(id);
        }
        
        public void CrearUsuario(PruebaTecnicaDB.ApplicationWeb.UsuarioService.UsuarioDto usuario) {
            base.Channel.CrearUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task CrearUsuarioAsync(PruebaTecnicaDB.ApplicationWeb.UsuarioService.UsuarioDto usuario) {
            return base.Channel.CrearUsuarioAsync(usuario);
        }
        
        public void EditarUsuario(PruebaTecnicaDB.ApplicationWeb.UsuarioService.UsuarioDto usuario, int id) {
            base.Channel.EditarUsuario(usuario, id);
        }
        
        public System.Threading.Tasks.Task EditarUsuarioAsync(PruebaTecnicaDB.ApplicationWeb.UsuarioService.UsuarioDto usuario, int id) {
            return base.Channel.EditarUsuarioAsync(usuario, id);
        }
        
        public void EliminarUsuario(System.Nullable<int> id) {
            base.Channel.EliminarUsuario(id);
        }
        
        public System.Threading.Tasks.Task EliminarUsuarioAsync(System.Nullable<int> id) {
            return base.Channel.EliminarUsuarioAsync(id);
        }
    }
}
